name: final_route_projcet_c16
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.8.5
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.4
  fluttertoast: ^8.2.4
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.00
  get_it: ^8.2.0
  provider: ^6.1.5+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.2.0
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  equatable: ^2.0.7
  google_sign_in: ^6.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/branding_image.png
    - assets/images/first_image.png
    - assets/images/second_image.png
    - assets/images/third_image.png
    - assets/images/fourth_image.png
    - assets/images/fifth_image.png
    - assets/images/sixth_image.png
    - assets/images/first_overlay.png
    - assets/images/second_overlay.png
    - assets/images/third_overlay.png
    - assets/images/fourth_overlay.png
    - assets/images/fifth_overlay.png
    - assets/images/sixth_overlay.png
    - assets/images/google.png
    - assets/images/flag_usa.png
    - assets/images/flag_egypt.png
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/avatar4.png
    - assets/images/avatar5.png
    - assets/images/avatar6.png
    - assets/images/avatar7.png
    - assets/images/avatar8.png
    - assets/images/avatar9.png

    - assets/icons/
    - assets/svg/
    - assets/lottie/
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"


